### ISSUE TITLE
how we can set generated file names to camel case?

### ISSUE THREAD

**Issue by mojtabamarashee** [eerimoq/pbtools#11]
hi
how we can set generated file names to camel case?
thanks

**Comment by eerimoq** [comment]
Only snake case is supported.

**Comment by mojtabamarashee** [comment]
but when this files are included(as header), the camel case is used.

**Comment by eerimoq** [comment]
Can you give an example? I don't quite understand what you mean.

**Comment by mojtabamarashee** [comment]
the problem is:
the input .proto file names are camel case and generated file names are snake case **but** when (generated header files) are included in each other, the are camel case.

for example in input file name is `TestPacket.proto` that has` DepPacket.proto` as dependency, generated file names are `test_proto.c` , `test_proto.h`,  `dep_packet.c` ,  `dep_packet.h`
but `test_proto.h` has included `DepPacket.h` that doesn't exist.



thanks

**Comment by eerimoq** [comment]
Ok I see. Now I understand. I'll have a look at it.

**Comment by eerimoq** [comment]
Should be fixed in 0.45.2. Thanks for improving pbtools!

**Comment by mojtabamarashee** [comment]
thanks
how I can install pbtools 0.45.2 (without pip)?

**Comment by mojtabamarashee** [comment]
the problem is resolved.
**thanks a lot**.
