### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by nickoala** [eerimoq/pbtools#13]
Thanks for the tool. I haven't taken a deep dive, but shallow impression gives me more confidence with pbtools than nanopb.

1. In `pbtools.h`, the following line causes Arduino IDE and g++ to complain. I can easily correct that by removing one `{` (and `}`), but am too lazy to create a pull request. Just let you know.
```C++
#ifdef __cplusplus
extern "C" {{
#endif
```

2. In the documentations, there are several places demonstrating the usage, e.g.
```
pbtools generate_c_source examples/hello_world/hello_world.proto
```
In my opinion, for people who aren't too familiar with Python and don't want to dig, it may be better to write:
```
python -m pbtools ...
 ```

Keep it up.

**Comment by eerimoq** [comment]
Fixed the first suggestion. The old version didn't even compile with clang on mac. Now it does.

Will not fix second suggestion now, but I agree that python packaging can be confusing sometimes.
