### ISSUE TITLE
Decode zero length messages doesn't reset to default values

### ISSUE THREAD

**Issue by thunder-hammer** [eerimoq/pbtools#14]
First of all, great tool. easy to use and it seems to just work!

I was using pbtools to decode messages that were encoded with a python message sender and I noticed some unexpected behavior.

This is my .proto file:

```
syntax = "proto3";
message simpleConfig{
    bool simpleBool = 1;
}
```

and my C file that I compiled with the generated files

```
#include "testproto.h"
#include <stdint.h>
#include <stdio.h>

uint8_t wrkspc[1024];
uint8_t nothing[1024];
uint8_t something[1024];

int main()
{
    struct simple_config_t * pConfig = simple_config_new(wrkspc, 1024);
    //default value is a 0
    printf("pConfig->simple_bool : %x\n", pConfig->simple_bool);
    //decode a nothing message
    simple_config_decode(pConfig, nothing, 0);
    //expect 0 get 0
    printf("pConfig->simple_bool : %x\n", pConfig->simple_bool);
    //setup a true message
    something[0] = 0x08;
    something[1] = 0x01;
    //decode the true message
    simple_config_decode(pConfig, something, 2);
    //expect 1 get 1
    printf("pConfig->simple_bool : %x\n", pConfig->simple_bool);
    //decode the default message again
    simple_config_decode(pConfig, nothing, 0);
    //expect 0 get 1?
    printf("pConfig->simple_bool : %x\n", pConfig->simple_bool);

}
```
Other test I ran seemed to indicate that it would keep the previous value in general.

I would expect a 0 length message decoded to just reset the values to defaults. For example, using protobufpal.com it looks like an empty message is decoded as a false even if the previous message was a true.

Let me know if I'm just doing something wrong too.

I attached my files.

[testproto.zip](https://github.com/eerimoq/pbtools/files/14274202/testproto.zip)

Thanks!

**Comment by eerimoq** [comment]
Hi!

You have to call `simple_config_new()` before every call to `simple_config_decode()` to initialize the message with default values it seems. It's probably a good idea to do that before every encode as well, but I have forgotten the details.

**Comment by thunder-hammer** [comment]
OK, that works. Thank you
