### ISSUE TITLE
Question about workspace/arena size and bytes fields

### ISSUE THREAD

**Issue by janedoe-lab** [eerimoq/pbtools#17]
This is really great project! Despite me just learning about protobuf, made it relatively painless so far!

I have a question about memory management. In my toy project I have a "wrapper message" with "oneof" messages inside. One thing I can't quite figure out is what is the best practice when dealing with bytes/string fields when it comes to  allocating memory for the workspace/arena. I am thinking that sizing based of sizeof(struct) + sizes of each individual dynamic field is so far the only way. But it means I can't really have generic code to allocate wrapper message and then work with specific messages elsewhere.

Perhaps there is a way to "realloc" workspace/arena when necessary. Is it possible to do something like:

`msg->base->heap_p->buf_p = realloc(msg->base->heap_p->buf_p, new_size)` whenever processing specific messages that are larger than default workspace size? 

Or perhaps there are better ways to handle it?

Also, can workspace/arena be re-used or it is always the best to alloc a new one for each new message struct?

Similarly, when decoding received packet, what is the best practice for calculating necessary workspace/arena size to decode it?

**Comment by eerimoq** [comment]
I would try to encode, and it it fails with memory error, make the workspace bigger and try again.

**Comment by janedoe-lab** [comment]
I actually just tried that and it seems to work fine for encoding/decoding.

What I am still struggling with - I am trying to split my code into separating allocation of Wrapper from allocation of the individual MessageX inside the wrapper. This way I can have a generic `encode_wrapper` function. Problem is - I can't figure out what is the proper workspace size  Ishould be using when allocating Wrapper message, considering that it may include different types of MessageX inside.

i.e. right now I am using something like this below

```
struct protobuf_wrapper_t *protocol_message_new(uint32_t channel_id)
{
    size_t workspace_size = 1024;
    uint8_t* workspace = malloc(workspace_size);

    struct protobuf_wrapper_t *wrapper_ptr;
    wrapper_ptr = protobuf_wrapper_new(workspace, workspace_size);

    wrapper_ptr->channel_id = channel_id;
    wrapper_ptr->timestamp = time(NULL);

    return wrapper_ptr;
}

struct protobuf_wrapper_t *protocol_log_message_new(uint32_t channel_id)
{
    struct protobuf_wrapper_t *wrapper_ptr = protocol_message_new(channel_id);
    
    if (protobuf_wrapper_log_alloc(wrapper_ptr) == -1)
    {
        DEBUG("Failed to allocate log message");
        protocol_message_free(wrapper_ptr);
        return NULL;
    }

    return wrapper_ptr;
}

int main()
{
    struct protobuf_wrapper_t *wrapper_ptr = protocol_log_message_new(1);
    if (wrapper_ptr == NULL)
    {
        return -1;
    }

    wrapper_ptr->message->log_level = 1;
    wrapper_ptr->message->message_text = "Hello, World!";

    // encode and send it

    free(wrapper_ptr->base.heap_p->buf_p);
    return 0;
}
```

I.e. I am using hardcoded 1024 bytes workspace. I wonder if this is the best possible approach? Does the fact that `message_text` field is variable size affect the size of workspace necessary?

**Comment by eerimoq** [comment]
Sorry, I don't have more ideas =)
