### ISSUE TITLE
example make generate fails

### ISSUE THREAD

**Issue by harryhaaren** [eerimoq/pbtools#3]
Hi,

With a clean checkout of the master branch, a cd to `examples/c/hello_world/` fails when I run `make generate`. PBTools installed using `pip3 install pbtools`. The error pasted below (with some manual filename `<snip>`'s), please let me know if there's something else I can try here? My (limited) python skillz didn't show an obvious problem...

```
$ <snip>/pbtools/examples/c/hello_world# make generate
rm -rf generated
mkdir -p generated
cd generated && \
    env PYTHONPATH=../../../.. \
        python3 -m pbtools generate_c_source ../hello_world.proto
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/<snip>/tests/pbtools/pbtools/__init__.py", line 4, in <module>
    from .parser import parse_file
  File "/<snip>/tests/pbtools/pbtools/parser.py", line 293
    self.name = f'({full_ident})'
                                ^
SyntaxError: invalid syntax
Makefile:14: recipe for target 'generate' failed
make: *** [generate] Error 1
```

Cheers, -Harry

**Comment by eerimoq** [comment]
pbtools requires Python 3.6+. What version do you have?

**Comment by harryhaaren** [comment]
OK, no problem, thanks for the quick reply. I'll close this, and go update my version of Python! Cheers, -Harry

**Comment by eerimoq** [comment]
@harryhaaren 

Great!

Let me know if you run into any problems using the package. It has not been used in any applications yet, so I expect some issues when people start using it.

Thanks!
