### ISSUE TITLE
How do you use the Proto object generated by pbtools.parse_file()?

### ISSUE THREAD

**Issue by ksemelka** [eerimoq/pbtools#8]
I am trying to get the list of messages/enums after parsing a .proto file, but can't seem to figure it out.

Here's what I'm trying:
```python
proto = pbtools.parse_file(filepath)
print(proto.messages)
```
Result: [<pbtools.parser.Message object at 0x0000025B7E714F10>]
Expected result: ["message_name_1", "message_name_2", etc.]

If you can help me understand how to get the names of the .proto messages and field names inside each message, I would be happy to open a PR to add documentation for this.

**Comment by eerimoq** [comment]
Script:
```python
import pbtools

proto = pbtools.parse_file('tests/files/address_book.proto')

for message in proto.messages:
    print(message.name)

    for field in message.fields:
        print(' ', field.name)
```
Output:
```
Person
  name
  id
  email
  phones
AddressBook
  people
```
